interface Alert {
  severity: string
  title?: string
  message: string
  feature?: string
  recommendation?: string
  value?: number
}

interface Props {
  alerts: Alert[]
  classicalRisk: number
  qmlRisk: number
  xrayFindings?: Alert[]
}

const SEVERITY_STYLES: Record<string, { bg: string; border: string; icon: string; color: string }> = {
  critical: { bg: '#ef444422', border: '#ef4444', icon: '🚨', color: '#fca5a5' },
  warning: { bg: '#f59e0b22', border: '#f59e0b', icon: '⚠️', color: '#fcd34d' },
  info: { bg: '#38bdf822', border: '#38bdf8', icon: 'ℹ️', color: '#93c5fd' },
  normal: { bg: '#10b98122', border: '#10b981', icon: '✅', color: '#6ee7b7' },
}

export default function AdvisoryPanel({ alerts, classicalRisk, qmlRisk, xrayFindings }: Props) {
  const allAlerts = [...(alerts || []), ...(xrayFindings || [])]

  return (
    <div className="rounded-xl p-5 border" style={{ background: '#111827', borderColor: '#2d3555' }}>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-base font-bold" style={{ color: '#f1f5f9' }}>
          🩺 QML Advisory for Clinician
        </h2>
        <div className="flex items-center gap-3 text-xs" style={{ color: '#94a3b8' }}>
          <span>Classical Risk: <strong style={{ color: classicalRisk < 0.5 ? '#10b981' : '#ef4444' }}>
            {(classicalRisk * 100).toFixed(1)}%
          </strong></span>
          <span>|</span>
          <span>QML Risk: <strong style={{ color: qmlRisk > 50 ? '#ef4444' : qmlRisk > 25 ? '#f59e0b' : '#10b981' }}>
            {qmlRisk}%
          </strong></span>
        </div>
      </div>

      <p className="text-xs mb-4" style={{ color: '#64748b' }}>
        These are advisory observations generated by the Quantum Entanglement Analysis.
        <strong style={{ color: '#f59e0b' }}> This is NOT a diagnosis.</strong> The QML system flags patterns that may warrant further clinical investigation.
      </p>

      <div className="space-y-3">
        {allAlerts.map((alert, i) => {
          const sev = SEVERITY_STYLES[alert.severity] || SEVERITY_STYLES.info
          return (
            <div
              key={i}
              className="rounded-lg p-4 border-l-4"
              style={{ background: sev.bg, borderLeftColor: sev.border }}
            >
              <div className="flex items-start gap-2">
                <span className="text-lg">{sev.icon}</span>
                <div className="flex-1">
                  <p className="font-semibold text-sm" style={{ color: sev.color }}>
                    {alert.title || alert.feature || 'Observation'}
                    {alert.value !== undefined && (
                      <span className="ml-2 text-xs font-normal" style={{ color: '#94a3b8' }}>
                        (score: {alert.value})
                      </span>
                    )}
                  </p>
                  <p className="text-xs mt-1" style={{ color: '#cbd5e1' }}>
                    {alert.message}
                  </p>
                  {alert.recommendation && (
                    <p className="text-xs mt-2 italic" style={{ color: '#94a3b8' }}>
                      Recommendation: {alert.recommendation}
                    </p>
                  )}
                </div>
              </div>
            </div>
          )
        })}
      </div>

      {classicalRisk < 0.5 && qmlRisk > 30 && (
        <div
          className="mt-4 rounded-lg p-4 text-xs"
          style={{ background: '#f59e0b11', border: '1px solid #f59e0b33', color: '#fcd34d' }}
        >
          <strong>Key Finding:</strong> Classical ML cleared this patient as healthy ({(classicalRisk * 100).toFixed(1)}% risk),
          but QML detected quantum correlation anomalies ({qmlRisk}% risk).
          This discrepancy suggests subtle multi-variable patterns that independent thresholds cannot capture.
          <strong> Doctor, please verify with additional clinical examination.</strong>
        </div>
      )}
    </div>
  )
}
